### ISSUE TITLE
documentation issue 6767 -> 7676

### ISSUE THREAD

**Issue by spjsschl** [noia-network/noia-node#1]
Hi in the documentation the default port is given as 6767 while it does seem to be 7676.

Additionally, is it necessary that each worker node has a publicly reachable IP address that exposes this port?

**Comment by Dancia** [comment]
Both 6767 and 7676 ports are correct. They both are used for clients (for now browsers) to connect to nodes. As documentation states, 6767 port is default when serving content from HTTP and 7676 is default when serving via WebSockets. Delivering of content using HTTP protocol is turned off by default so only 7676 is used for ws connections.

The IP:PORT should be reachable by clients.

**Comment by Pierozi** [comment]
Could be possible to customize the Public Node IP?
Because the detected IP from the log `node_ip=1.2.3.4` are not necessarily the good one.
If I want NAT the port for worldwide access, I'll have dedicated IP.

**Comment by Dancia** [comment]
@Pierozi Reasonable request. Please create separate issue, will add to TODO list. Thanks!
