### ISSUE TITLE
wallet providerUrl

### ISSUE THREAD

**Issue by rikius** [noia-network/noia-node#4]
wallet.providerUrl is required, what kind of url need to use?

Readme mentioned this:
  // One option for test purposes is to use https://ropsten.infura.io infrastructure.
  walletProviderUrl: "https://example-wallet-provider.io/API_KEY"

but htis is a testing url what kind of production wallet url is?

Thanks.

**Comment by Dancia** [comment]
There is a bug in documentation. I will update documentation soon. The documention is assuming that skipBlockchain is false by default, which is not true in latest updates.

`walletProviderUrl` is required only if connection to master is being made through the blockchain. Currently by default we have enabled `skipBlockchain` parameter, meaning that `walletProviderUrl` parameter is not required in this case. Just enter `masterAddress` parameter for master address and you are good to go. To receive AIRDROP reward, also specify your `walletAddress` wallet address.

I suggest first trying out [noia-node-terminal](https://github.com/noia-network/noia-node-terminal )  or [https://github.com/noia-network/noia-node-gui/](noia-node-gui) ([available releases](https://github.com/noia-network/noia-node-gui/releases))

**Comment by rikius** [comment]
Thanks it hellped.
